match_groups = [
    "予選y",
    "勝者qf1",
    "勝者qf2",
    "勝者qf3",
    "勝者qf4",
    "勝者sf1",
    "敗者y12",
    "敗者y13",
    "敗者y14",
    "敗者y15",
    "敗者y16",
    "敗者y17",
    "敗者qf5",
    "敗者qf6",
    "敗者qf7",
    "敗者qf8",
    "敗者qf9",
    "敗者qf10",
    "敗者sf2",
    "敗者sf3",
    "敗者sf4",
    "決勝fin",
]

match_group_mapping = {
    "予選y": [f"y{i}-1" for i in range(1, 12)],
    "勝者qf1": [f"qf1-{i}" for i in range(1, 5)],
    "勝者qf2": [f"qf2-{i}" for i in range(1, 5)],
    "勝者qf3": [f"qf3-{i}" for i in range(1, 5)],
    "勝者qf4": [f"qf4-{i}" for i in range(1, 5)],
    "勝者sf1": [f"sf1-{i}" for i in range(1, 5)],
    "敗者y12": [f"y12-{i}" for i in range(1, 5)],
    "敗者y13": [f"y13-{i}" for i in range(1, 5)],
    "敗者y14": [f"y14-{i}" for i in range(1, 5)],
    "敗者y15": [f"y15-{i}" for i in range(1, 2)],
    "敗者y16": [f"y16-{i}" for i in range(1, 2)],
    "敗者y17": [f"y17-{i}" for i in range(1, 5)],
    "敗者qf5": [f"qf5-{i}" for i in range(1, 2)],
    "敗者qf6": [f"qf6-{i}" for i in range(1, 2)],
    "敗者qf7": [f"qf7-{i}" for i in range(1, 2)],
    "敗者qf8": [f"qf8-{i}" for i in range(1, 2)],
    "敗者qf9": [f"qf9-{i}" for i in range(1, 2)],
    "敗者qf10": [f"qf10-{i}" for i in range(1, 2)],
    "敗者sf2": [f"sf2-{i}" for i in range(1, 2)],
    "敗者sf3": [f"sf3-{i}" for i in range(1, 2)],
    "敗者sf4": [f"sf4-{i}" for i in range(1, 2)],
    "決勝fin": [f"fin-{i}" for i in range(1, 5)],
}
